import type { Metadata } from "next";
import "./globals.css";
import LayoutButton from "./components/layout-button";
import Header from "./components/header";
import TimeRefresh from "./components/time-refresh";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="pt-[90px] px-3">
        <TimeRefresh />
        <Header />
        {children}
        <div className="fixed bottom-[18px] left-1/2 transform -translate-x-1/2 w-[80%] h-20 bg-[#E66C32] rounded-full shadow-lg flex justify-around items-center">
          <LayoutButton location="Home" to="/" />
          <LayoutButton location="Bus" to="bus" />
          <LayoutButton location="Food" to="food" />
          <LayoutButton location="🖐️" to="profile" />
        </div>
      </body>
    </html>
  );
}
